-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Employeers"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    company_name character varying(100) NOT NULL,
    web_site character varying(100) NOT NULL,
    admin_verify boolean NOT NULL,
    jobs_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Employees"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."JobSeekers"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying(20) NOT NULL,
    last_name character varying(20) NOT NULL,
    nationality_number character varying(11) NOT NULL,
    birth_year integer NOT NULL,
    employeers_id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Jobs"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(100) NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Users"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(100) NOT NULL,
    password character varying(50) NOT NULL,
    email_verify boolean NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."Employeers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Employees"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY (employeers_id)
    REFERENCES public."Employeers" (id)
    NOT VALID;


ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Jobs"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;

END;